steps:
  # Set up env
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'DATABASE_URI=${_DATABASE_URI}'
      - 'AUTH_SECRET=${_AUTH_SECRET}'
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dentist-backend:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dentist-backend:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dentist-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dentist-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
images:
  - 'gcr.io/$PROJECT_ID/dentist-backend:$COMMIT_SHA'
timeout: 900s
